import './globals.css'
import './404.css'
import './preloader.css'
import '../styles/layout/Header/header.scss'
import '../styles/layout/Header/profile.scss'
import '../styles/layout/Footer/footer.scss'
import '../styles/main.scss'
import '../styles/auth.scss'
import '../styles/catalog.scss'
import '../styles/utils/_ui.scss'
import '../styles/mobileFilter.scss'
import '../styles/cart.scss'
import '../styles/product.scss'
import '../styles/store.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Layout } from '@/components/Layout'
import { Providers } from './_redux/provider'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Raftel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script
          src="https://apis.google.com/js/api.js"
          strategy="beforeInteractive"
        />
        <Providers>
          <Layout>
            <main className='wrapper'>
              {children}
            </main>
          </Layout>
        </Providers>
      </body>
    </html>
  )
}
